exports.STATUS_PAUSED = 'PAUSED';
exports.STATUS_PLAYING = 'PLAYING';
exports.STATUS_FINISHED = 'FINISHED';

exports.TURN_SECONDS = 10;
exports.GAME_START_COUNTDOWN = 30;

exports.COLOR_NEUTRAL = -1;

