version: "2"

services:
  postgres:
    restart: always
    build: ./postgres
    # image: postgres:9.6.9
    environment:
      POSTGRES_DB: "nodice"
      POSTGRES_USER: "bgrosse"
    ports: [ "5433:5432" ]
    volumes:
      - ~/data-postgres:/var/lib/postgresql/data
  edice:
    restart: always
    # network_mode: host
    build:
      context: ./edice
      dockerfile: Dockerfile
      args:
        ENV: $ENV
    # env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./data/proxy_params:/etc/nginx/proxy_params
      # - ./data/nginx/default.conf.local:/etc/nginx/conf.d/default.conf
      # - /etc/letsencrypt/:/etc/letsencrypt/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - emqx
      - nodice
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  emqx:
    image: emqx/emqx:v3.0.0
    ports:
      - "8083:8083"
      - "8081:8080"
      - "18083:18083"
      - "11883:11883"
      - "1883:1883"
  nodice:
    build: .
    ports: ["5001:5001"]
    env_file: .env
    links:
      - postgres
      - emqx

networks:
  default:
    external:
      name: qdice
