version: "2"

services:
  postgres:
    restart: always
    build: ./postgres
    environment:
      POSTGRES_DB: "nodice"
      POSTGRES_USER: "bgrosse"
    ports: [ "5433:5432" ]
    volumes:
      - ~/data-postgres:/var/lib/postgresql/data
  emqx:
    image: emqx/emqx:v3.0.0
    ports:
      - "8083:8083"
      - "8081:8080"
      - "18083:18083"
      - "11883:11883"
      - "1883:1883"
  nodice:
    restart: always
    image: bgrosse/qdice:latest
    ports: ["5001:5001"]
    env_file: .env
    volumes:
      - statics:/usr/src/edice/dist
    depends_on:
      - postgres
      - emqx
  telegram:
    restart: always
    image: bgrosse/qdice:latest
    env_file: .env
    volumes:
      - ~/data-avatars:/avatars
    depends_on:
      - postgres
      - emqx
    command: "node telegram.js"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
      args:
        ENV: $ENV
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - statics:/var/www/qdice.wtf
      - ~/data-avatars:/var/www/qdice.wtf/pictures
      - ./data/logs/nginx:/var/log/nginx
      - ./data/goaccess/html:/var/www/goaccess
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - emqx
      - nodice
      - certbot
  goaccess:
    # build:
      # context: .
      # dockerfile: ./Dockerfile.goaccess
    image: allinurl/goaccess
    restart: always
    volumes:
      - ./data/goaccess/goaccess.conf:/srv/data/goaccess.conf
      - ./data/goaccess/html:/srv/report
      - ./data/logs/nginx:/srv/logs
    command: "--no-global-config --config-file=/srv/data/goaccess.conf"
    ports:
      - "7890:7890"
    cap_drop:
      - all
    depends_on:
      - nginx

networks:
  default:
    external:
      name: qdice

volumes:
  statics:

