# node.js server build

FROM node:12.14.1-alpine AS server

WORKDIR /usr/src/nodice
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production

COPY edice/scripts/generate-maps.js ./scripts/generate-maps.js
COPY edice/maps ./edice/maps
RUN node ./scripts/generate-maps.js ./edice/maps/

COPY tsconfig.json *.ts tables.config.js ./
COPY table ./table

WORKDIR /usr/src/nodice
CMD ["yarn", "ts-node", "beancounter.ts"]

