version: "2"

services:
  postgres:
    ports:
      - 5433:5432
  emqx:
    ports:
      - 8083:8083
      - 1883:1883
      - 8082:8080
      - 18083:18083
      - 11883:11883
  nginx:
    image: bgrosse/qdice:frontend-local
  renderer:
    image: zenato/puppeteer-renderer
    restart: always
    ports:
      - "3000:3000"

