version: "2"

services:
  postgres:
    restart: always
    build: ./postgres
    environment:
      POSTGRES_DB: "nodice"
      POSTGRES_USER: "bgrosse"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: [ "5433:5432" ]
    volumes:
      - ~/data-postgres:/var/lib/postgresql/data
  emqx:
    image: emqx/emqx:v3.2.7
    environment:
      EMQX_LOADED_PLUGINS: "emqx_management,emqx_auth_username,emqx_recon,emqx_retainer,emqx_dashboard"
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: ${EMQX_DASHBOARD_PASSWORD}
      # EMQX_ALLOW_ANONYMOUS: "true"
      # EMQX_AUTH__JWT__SECRET: ${JWT_SECRET}
      # EMQX_AUTH__JWT__FROM: "password"
      EMQX_AUTH__USER__1__USERNAME: ${MQTT_USERNAME}
      EMQX_AUTH__USER__1__PASSWORD: ${MQTT_PASSWORD}
    ports:
      - "8083:8083" # http for clients
      - "1883:1883" # tcp for nodejs
      - "8082:8080" # API mgmnt
      - "18666:18083" # dashboard
      - "11883:11883" # ???
    volumes:
      - ./data/emqx/acl.conf:/opt/emqx/etc/acl.conf:ro
  nodice:
    restart: always
    image: bgrosse/qdice:latest
    ports: ["5001:5001"]
    env_file: .env
    volumes:
      - statics:/usr/src/edice/dist
      - ~/data-avatars:/avatars
    depends_on:
      - postgres
      - emqx
  telegram:
    restart: always
    image: bgrosse/qdice:latest
    env_file: .env
    volumes:
      - ~/data-avatars:/avatars
    depends_on:
      - postgres
      - emqx
    command: "node telegram.js"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
      args:
        ENV: $ENV
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - statics:/var/www/qdice.wtf
      - ~/data-avatars:/var/www/qdice.wtf/pictures:ro
      - ./data/logs/nginx:/var/log/nginx
      - goaccess:/var/www/goaccess:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - emqx
      - nodice
      - certbot
  goaccess:
    # build:
      # context: .
      # dockerfile: ./Dockerfile.goaccess
    image: allinurl/goaccess
    restart: always
    volumes:
      - ./data/goaccess/goaccess.conf:/srv/data/goaccess.conf:ro
      - goaccess:/srv/report:rw
      - ./data/logs/nginx:/srv/logs:ro
    command: "--no-global-config --config-file=/srv/data/goaccess.conf"
    ports:
      - "7890:7890"
    cap_drop:
      - all
    depends_on:
      - nginx

networks:
  default:
    external:
      name: qdice

volumes:
  statics:
  goaccess:

