version: "2"

services:
  postgres:
    restart: always
    build: ./postgres
    environment:
      POSTGRES_DB: "nodice"
      POSTGRES_USER: "bgrosse"
    ports: [ "5433:5432" ]
    volumes:
      - ~/data-postgres:/var/lib/postgresql/data
  emqx:
    image: emqx/emqx:v3.0.0
    ports:
      - "8083:8083"
      - "8081:8080"
      - "18083:18083"
      - "11883:11883"
      - "1883:1883"
  nodice:
    restart: always
    image: bgrosse/qdice
    ports: ["5001:5001"]
    env_file: .env
    volumes:
      - statics:/usr/src/edice/dist
    links:
      - postgres
      - emqx
  nginx:
    restart: always
    image: nginx:mainline
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/proxy_params:/etc/nginx/proxy_params
      - ./data/nginx/default.conf.${ENV}:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - statics:/var/www/qdice.wtf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - emqx
      - nodice
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  default:
    external:
      name: qdice

volumes:
  statics:

