# node.js server build

FROM zenato/puppeteer-renderer

WORKDIR /usr/src/nodice
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production

COPY tsconfig.json *.ts tables.config.js ./
COPY table ./table

WORKDIR /usr/src/nodice
CMD ["yarn", "ts-node", "beancounter.ts"]

