version: "2"

services:
  postgres:
    ports:
      - 5433:5432
  emqx:
    ports:
      - 8083:8083
      - 1883:1883
      - 18083:18083
      - 11883:11883
  redis:
    ports:
      - 6380:6379
  haproxy:
    environment:
      - STAGING=true
      - CERT1=
    volumes:
      - ./haproxy/haproxy.local.cfg:/etc/haproxy/haproxy.cfg
  matrix:
    ports:
      - 8008:8008

