module.exports = {
  tables: [
    {
      tag: 'Serrano',
      name: 'Serrano',
      playerSlots: 7,
      startSlots: 2,
      points: 0,
      stackSize: 8,
      noFlagRounds: 5,
    },
    //{
      //tag: 'DeLucía',
      //name: 'De Lucía',
      //playerSlots: 7,
      //startSlots: 3,
      //points: 100,
      //stackSize: 8,
      //noFlagRounds: 5,
    //},
    //{
      //tag: 'Melchor',
      //name: 'Melchor',
      //playerSlots: 5,
      //startSlots: 2,
      //points: 0,
      //stackSize: 4,
      //noFlagRounds: 1,
    //},
    //{
      //tag: 'Miño',
      //name: 'Miño',
      //playerSlots: 5,
      //startSlots: 2,
      //points: 0,
      //stackSize: 4,
      //noFlagRounds: 5,
    //},
    //{
      //tag: 'Sabicas',
      //name: 'Sabicas',
      //playerSlots: 9,
      //startSlots: 4,
      //points: 200,
      //stackSize: 8,
      //noFlagRounds: 5,
    //},
  ],
};

