version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: git config --file=.gitmodules submodule.edice.url git@bitbucket.org:easy-rider/edice.git
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build all containers
          command: |
            set -x
            docker-compose build
      - run:
          name: Create network
          command: docker network create qdice
      - run:
          name: Start all containers
          command: |
            set -x
            docker-compose up -d

      - run:
          name: Build e2e
          command: |
            docker build ./e2e -t qdice2e
      - run:
          name: Build e2e
          command: |
            docker run --network qdice -e E2E_URL=http://edice qdice2e yarn test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build

