version: 2.1

orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
      - image: buildkite/puppeteer:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: git config --file=.gitmodules submodule.edice.url git@bitbucket.org:easy-rider/edice.git
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build all containers
          command: |
            set -x
            docker-compose build
      - run:
          name: Start all containers
          command: |
            set -x
            docker-compose up -d

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-e2e-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          working_directory: ./e2e
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-e2e-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: e2e
          working_directory: ./e2e
          command: yarn jest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

